### ISSUE TITLE
Fail to start two sessions of Field simultaneously

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#64]
Added to command line: -noChecks 1
deleted from f_mac: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 

Exception thrown in main of fieldbox.FieldBox
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at fieldagent.Trampoline.main(Trampoline.java:219)
Caused by: java.lang.IllegalArgumentException: need server for boxbrowser
	at fielded.boxbrowser.BoxBrowser.lambda$loaded$1386(BoxBrowser.java:32)
	at fielded.boxbrowser.BoxBrowser$$Lambda$305/369805307.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at fielded.boxbrowser.BoxBrowser.loaded(BoxBrowser.java:32)
	at fieldbox.Open.lambda$new$209(Open.java:332)
	at fieldbox.Open$$Lambda$302/731243659.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at fieldbox.Open.<init>(Open.java:331)
	at fieldbox.FieldBox.main(FieldBox.java:38)
	... 5 more

**Comment by marcdownie** [comment]
We have three fixed ports: 1) the default launch script adds a (fixed) debug port -- java won't launch if it can't open the port. 2) there's a plugin that uses a fixed port for browsing boxes and 3) the text editor is bootstrapped off of a fixed port webserver.
